### PR TITLE
Fix for HealOtherPlayer exploit, also fix #1309

### LINKED ISSUE #1309: "Invalid command entered" when no command entered
Maybe this was caused by fixing security issues(?), error message is also displayed when I just pressed 'Enter' key (or whitespace only). It's a bit annoying.

Is there any way to avoid this, something like

if (cmdText.Trim() == "")
{
    return true;
}

at HandleCommand() in TShockAPI/Commands.cs?

### PR DESCRIPTION
**Pull request by Simon311**
Fix for HealOtherPlayer exploit, also fix #1309.
The code should self-explanatory.

### CODE REVIEW

**Comment by Simon311** [comment]
Needs some fixing, one more commit incoming

**Comment by Simon311** [comment]
This is tested.

File: TShockAPI/ConfigFile.cs [hunk 1]
```diff
@@ -295,6 +295,10 @@ public class ConfigFile
 		[Description("Disable a player if this number of projectiles is created within 1 second.")]
 		public int ProjectileThreshold = 50;
 
+		/// <summary>ProjectileThreshold - Disables a player if this number of projectiles is created within 1 second.</summary>
+		[Description("Disable a player if this number of projectiles is created within 1 second.")]
```
Comment (WhiteXZ) [inline TShockAPI/ConfigFile.cs]: Description is incorrect
